version: 2.1

jobs:
  checks:
    docker:
      - image: cimg/rust:1.56.1-node
    steps:
      - checkout
      - run:
          name: Check formatting
          command: "cargo fmt -- --config-path .circleci/fmt.ini --check"

  coverage:
    docker:
      - image: corebreaker/rust-devtools-circleci:rust1.56.1-v0.1.0
    steps:
      - checkout
      - run:
          name: Make coverage
          command: ".circleci/coverage.sh"
      - run:
          name: Upload Coverage Result To Coveralls
          command: "coveralls -D target -i target/coverage/coveralls.json circleci"
      - store_artifacts:
          path: target/coverage
  test:
    docker:
      - image: cimg/rust:1.56.1
    steps:
      - restore_cache:
          key: project-cache
      - checkout
      - run:
          name: Run tests
          command: "cargo test"
      - save_cache:
          key: project-cache
          paths:
            - "~/.cargo"

workflows:
  coverage:
    jobs:
      - coverage

  all-tests:
    jobs:
      - checks
      - test
