version: 2.1

jobs:
  checks:
    docker:
      - image: cimg/rust:1.59-node
    steps:
      - checkout
      - run:
          name: Check formatting
          command: "cargo fmt -- --config-path .circleci/fmt.ini --check"

  coverage:
    docker:
      - image: corebreaker/rust-devtools-circleci:rust1.59-v0.3.0
    steps:
      - checkout
      - run:
          name: Make coverage
          command: "coverage.sh"
      - run:
          name: Upload Coverage Result To Coveralls
          command: "coveralls -D target -i target/coverage/coveralls.json circleci"
      - store_artifacts:
          path: target/coverage

  test:
    docker:
      - image: cimg/rust:1.59
    steps:
      - checkout
      - run:
          name: Run tests
          command: "CARGO_NET_GIT_FETCH_WITH_CLI=true cargo test"

workflows:
  version: 2
  coverage:
    filters:
      branches:
        only: main
    jobs:
      - coverage

  all-tests:
    jobs:
      - checks
      - test
