edition = "2021"
max_width = 120
use_small_heuristics = "Default"
brace_style = "PreferSameLine"
comment_width = 120
condense_wildcard_suffixes = true
control_brace_style = "AlwaysSameLine"
error_on_line_overflow = true
error_on_unformatted = true
fn_params_layout = "Tall"
format_code_in_doc_comments = true
format_macro_bodies = true
format_macro_matchers = true
imports_granularity = "Crate"
indent_style = "Block"
inline_attribute_width = 0
match_arm_blocks = true
match_arm_leading_pipes = "Never"
match_block_trailing_comma = false
merge_derives = true
reorder_impl_items = true
space_after_colon = true
space_before_colon = false
spaces_around_ranges = false
tab_spaces = 4
trailing_comma = "Vertical"
trailing_semicolon = true
type_punctuation_density = "Wide"
use_field_init_shorthand = true
use_try_shorthand = true
wrap_comments = false
